---
title: "Population-weighted centres of local administrative units (LAU) in Europe"
description: |
  If you need the coordinates of a location, where do you put the centre?
author:
  - name: Giorgio Comai 
    url: https://giorgiocomai.eu
    affiliation: OBCT/EDJNet
    affiliation_url: https://www.europeandatajournalism.eu/
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```


__N.B. This is a work in progress. Ensure that the data provided are fit for purpose.__

This repository presents datasets of the population-weighted centres of local administrative units in Europe, the scripts used to generate them with different approaches, as well as details on quality checks and peculiarities of the data.

It also tries to facilitate matching a given local administrative unit to their [correspondent NUTS region](https://ec.europa.eu/eurostat/web/nuts/local-administrative-units).

## Motivation

- when showing data points of a local adminsitrative unit (or other territorial boundaries) we often need a specific point on a map to show relevant information. Where should that point fall?
- when taking values from a data grid it is often useful to have a specific set of coordinates: which should that be for local administrative units?

Check out the following blog post for context:

[How to find the population-weighted centre of local administrative units](https://medium.com/european-data-journalism-network/how-to-find-the-population-weighted-centre-of-local-administrative-units-a0d198fc91f7)

## Data availability

This repository covers local administrative units as distributed by Europen Union's [Gisco services](https://gisco-services.ec.europa.eu/distribution/v2/lau/download/), and tentatively LAUs in nieghbouring jurisdictions.

The main determinants of data availability are:

- inclusion of relevant country in the [LAU datasets](https://gisco-services.ec.europa.eu/distribution/v2/lau/download/) for the relevant year
- coverage by the EU population grid [as distributed by the EU's Gisco services](https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/population-distribution-demography/geostat)


Additional sources for the population grid include [High Resolution Population Density Maps distributed by Facebook](https://data.humdata.org/organization/facebook).

[GADM for administrative boundaries](https://gadm.org/).

## Sources

### Local Administrative Units (LAU)

The original dataset of Local Administrative Units (LAU) can be downloaded from the following link:
https://gisco-services.ec.europa.eu/distribution/v2/lau/download/

LAU can be matched to NUTS via concordance tables:
https://ec.europa.eu/eurostat/web/nuts/local-administrative-units

### Population grid

The population grid can be downloaded from the following link:
https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/population-distribution-demography/geostat

Details on how the population grid was generated as well as context on the reliability of the data is included in the factsheet that can be downloaded with the latest available dataset (at the time of writing), based on 2018 data and released in 2021:

## Licensing

© EuroGeographics for the administrative boundaries (see [full licensing details for LAUs](https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units))

Licensing for the population grid dataset varies depening on year and the country originally providing the data. See [the relevant page for full details](https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/population-distribution-demography). 

Facebook's [High Resolution Population Density Maps](https://data.humdata.org/organization/facebook) are distributed with a CC-BY license.


The processed dataset is distributed with a CC-BY license, crediting [EDJNet](https://europeandatajournalism.eu/) and, if relevant, linking to this repository.




